create table BASE_CATEGORIES(category_id NUMBER NOT NULL, name VARCHAR2(4000), PRIMARY KEY (category_id));

INSERT ALL
 into BASE_CATEGORIES (category_id, name) VALUES (0, '#System')
 into BASE_CATEGORIES (category_id, name) VALUES (1, 'Owner')
 into BASE_CATEGORIES (category_id, name) VALUES (2, 'Celestial')
 into BASE_CATEGORIES (category_id, name) VALUES (3, 'Station')
 into BASE_CATEGORIES (category_id, name) VALUES (4, 'Material')
 into BASE_CATEGORIES (category_id, name) VALUES (5, 'Accessories')
 into BASE_CATEGORIES (category_id, name) VALUES (6, 'Ship')
 into BASE_CATEGORIES (category_id, name) VALUES (7, 'Module')
 into BASE_CATEGORIES (category_id, name) VALUES (8, 'Charge')
 into BASE_CATEGORIES (category_id, name) VALUES (9, 'Blueprint')
 into BASE_CATEGORIES (category_id, name) VALUES (10, 'Trading')
 into BASE_CATEGORIES (category_id, name) VALUES (11, 'Entity')
 into BASE_CATEGORIES (category_id, name) VALUES (14, 'Bonus')
 into BASE_CATEGORIES (category_id, name) VALUES (16, 'Skill')
 into BASE_CATEGORIES (category_id, name) VALUES (17, 'Commodity')
 into BASE_CATEGORIES (category_id, name) VALUES (18, 'Drone')
 into BASE_CATEGORIES (category_id, name) VALUES (20, 'Implant')
 into BASE_CATEGORIES (category_id, name) VALUES (22, 'Deployable')
 into BASE_CATEGORIES (category_id, name) VALUES (23, 'Starbase')
 into BASE_CATEGORIES (category_id, name) VALUES (24, 'Reaction')
 into BASE_CATEGORIES (category_id, name) VALUES (25, 'Asteroid')
 into BASE_CATEGORIES (category_id, name) VALUES (26, 'WorldSpace')
 into BASE_CATEGORIES (category_id, name) VALUES (29, 'Abstract')
 into BASE_CATEGORIES (category_id, name) VALUES (30, 'Apparel')
 into BASE_CATEGORIES (category_id, name) VALUES (32, 'Subsystem')
 into BASE_CATEGORIES (category_id, name) VALUES (34, 'Ancient Relics')
 into BASE_CATEGORIES (category_id, name) VALUES (35, 'Decryptors')
 into BASE_CATEGORIES (category_id, name) VALUES (39, 'Infrastructure Upgrades')
 into BASE_CATEGORIES (category_id, name) VALUES (40, 'Sovereignty Structures')
 into BASE_CATEGORIES (category_id, name) VALUES (41, 'Planetary Industry')
 into BASE_CATEGORIES (category_id, name) VALUES (42, 'Planetary Resources')
 into BASE_CATEGORIES (category_id, name) VALUES (43, 'Planetary Commodities')
 into BASE_CATEGORIES (category_id, name) VALUES (46, 'Orbitals')
 into BASE_CATEGORIES (category_id, name) VALUES (49, 'Placeables')
 into BASE_CATEGORIES (category_id, name) VALUES (53, 'Effects')
 into BASE_CATEGORIES (category_id, name) VALUES (54, 'Lights')
 into BASE_CATEGORIES (category_id, name) VALUES (59, 'Cells')
 into BASE_CATEGORIES (category_id, name) VALUES (63, 'Special Edition Assets')
 into BASE_CATEGORIES (category_id, name) VALUES (65, 'Structure')
 into BASE_CATEGORIES (category_id, name) VALUES (66, 'Structure Module')
 into BASE_CATEGORIES (category_id, name) VALUES (87, 'Fighter')
 into BASE_CATEGORIES (category_id, name) VALUES (91, 'SKINs')
 into BASE_CATEGORIES (category_id, name) VALUES (2100, 'Expert Systems')
 into BASE_CATEGORIES (category_id, name) VALUES (2107, 'Mining')
 into BASE_CATEGORIES (category_id, name) VALUES (350001, 'Infantry')
select 1 from DUAL;