whenever sqlerror exit failure

create table BASE_CATEGORIES(category_id NUMBER NOT NULL, name VARCHAR2(4000), PRIMARY KEY (category_id));

INSERT INTO BASE_CATEGORIES (category_id, name)
          SELECT 0, '#System' FROM DUAL
UNION ALL SELECT 1, 'Owner' FROM DUAL
UNION ALL SELECT 2, 'Celestial' FROM DUAL
UNION ALL SELECT 3, 'Station' FROM DUAL
UNION ALL SELECT 4, 'Material' FROM DUAL
UNION ALL SELECT 5, 'Accessories' FROM DUAL
UNION ALL SELECT 6, 'Ship' FROM DUAL
UNION ALL SELECT 7, 'Module' FROM DUAL
UNION ALL SELECT 8, 'Charge' FROM DUAL
UNION ALL SELECT 9, 'Blueprint' FROM DUAL
UNION ALL SELECT 10, 'Trading' FROM DUAL
UNION ALL SELECT 11, 'Entity' FROM DUAL
UNION ALL SELECT 14, 'Bonus' FROM DUAL
UNION ALL SELECT 16, 'Skill' FROM DUAL
UNION ALL SELECT 17, 'Commodity' FROM DUAL
UNION ALL SELECT 18, 'Drone' FROM DUAL
UNION ALL SELECT 20, 'Implant' FROM DUAL
UNION ALL SELECT 22, 'Deployable' FROM DUAL
UNION ALL SELECT 23, 'Starbase' FROM DUAL
UNION ALL SELECT 24, 'Reaction' FROM DUAL
UNION ALL SELECT 25, 'Asteroid' FROM DUAL
UNION ALL SELECT 26, 'WorldSpace' FROM DUAL
UNION ALL SELECT 29, 'Abstract' FROM DUAL
UNION ALL SELECT 30, 'Apparel' FROM DUAL
UNION ALL SELECT 32, 'Subsystem' FROM DUAL
UNION ALL SELECT 34, 'Ancient Relics' FROM DUAL
UNION ALL SELECT 35, 'Decryptors' FROM DUAL
UNION ALL SELECT 39, 'Infrastructure Upgrades' FROM DUAL
UNION ALL SELECT 40, 'Sovereignty Structures' FROM DUAL
UNION ALL SELECT 41, 'Planetary Industry' FROM DUAL
UNION ALL SELECT 42, 'Planetary Resources' FROM DUAL
UNION ALL SELECT 43, 'Planetary Commodities' FROM DUAL
UNION ALL SELECT 46, 'Orbitals' FROM DUAL
UNION ALL SELECT 49, 'Placeables' FROM DUAL
UNION ALL SELECT 53, 'Effects' FROM DUAL
UNION ALL SELECT 54, 'Lights' FROM DUAL
UNION ALL SELECT 59, 'Cells' FROM DUAL
UNION ALL SELECT 63, 'Special Edition Assets' FROM DUAL
UNION ALL SELECT 65, 'Structure' FROM DUAL
UNION ALL SELECT 66, 'Structure Module' FROM DUAL
UNION ALL SELECT 87, 'Fighter' FROM DUAL
UNION ALL SELECT 91, 'SKINs' FROM DUAL
UNION ALL SELECT 2100, 'Expert Systems' FROM DUAL
UNION ALL SELECT 2107, 'Mining' FROM DUAL
UNION ALL SELECT 350001, 'Infantry' FROM DUAL
;
