package fr.guiguilechat.jcelechat.programs.showattributes;

import java.io.IOException;

import fr.guiguilechat.jcelechat.model.sde.EveType;
import fr.guiguilechat.jcelechat.model.sde.TypeIndex;

public class ConvertNameId {

	public static void main(String[] args) throws IOException {
		String in = "10MN Y-S8 Compact Afterburner\n" + "125mm Light Carbine Repeating Cannon I\n"
				+ "125mm Light Prototype Automatic Cannon\n"
				+ "125mm Prototype Gauss Gun\n" + "1400mm Gallium Cannon\n" + "150mm Carbide Railgun I\n"
				+ "150mm Prototype Gauss Gun\n"
				+ "18th Tier Overseer's Personal Effects\n"
				+ "1st Tier Overseer's Personal Effects\n"
				+ "200mm Carbide Railgun I\n"
				+ "200mm Light Carbine Repeating Cannon I\n"
				+ "220mm Medium Carbine Repeating Cannon I\n"
				+ "250mm 'Scout' Accelerator Cannon\n"
				+ "250mm Carbide Railgun I\n"
				+ "250mm Light Carbine Howitzer I\n"
				+ "250mm Light Gallium Cannon\n"
				+ "280mm Gallium Cannon\n"
				+ "2nd Tier Overseer's Personal Effects\n"
				+ "3rd Tier Overseer's Personal Effects\n"
				+ "425mm 'Scout' Accelerator Cannon\n"
				+ "425mm Medium Carbine Repeating Cannon I\n"
				+ "425mm Medium Gallium Machine Gun\n"
				+ "425mm Medium Prototype Automatic Cannon\n"
				+ "4th Tier Overseer's Personal Effects\n"
				+ "50MN Cold-Gas Enduring Microwarpdrive\n"
				+ "5MN Quad LiF Restrained Microwarpdrive\n"
				+ "5th Tier Overseer's Personal Effects\n"
				+ "650mm Medium Carbine Howitzer I\n"
				+ "650mm Medium Gallium Cannon\n"
				+ "720mm Carbine Howitzer I\n"
				+ "720mm Gallium Cannon\n"
				+ "720mm Prototype Siege Cannon\n"
				+ "75mm Carbide Railgun I\n"
				+ "7th Tier Overseer's Personal Effects\n"
				+ "800mm Heavy 'Jolt' Repeating Cannon I Blueprint\n"
				+ "8th Tier Overseer's Personal Effects\n"
				+ "Advanced 'Limos' Heavy Missile Bay I\n"
				+ "AE-K Compact Drone Damage Amplifier\n"
				+ "Analog Panel\n"
				+ "Ancient Coordinates Database\n"
				+ "Anode Light Ion Particle Cannon I\n" + "Anode Neutron Particle Cannon I\n"
				+ "Arbalest Compact Light Missile Launcher\n"
				+ "Arquebus' Heavy Beam Laser I Blueprint\n"
				+ "Auxiliary Parts\n"
				+ "Compact EM Shield Amplifier\n"
				+ "Compact EM Shield Hardener\n"
				+ "Compact Explosive Shield Amplifier\n"
				+ "Compact Explosive Shield Hardener\n"
				+ "Compact Kinetic Shield Amplifier\n"
				+ "Compact Kinetic Shield Hardener\n"
				+ "Compact Multispectrum Shield Hardener\n"
				+ "Compact Thermal Shield Amplifier\n"
				+ "Copasetic Compact Shield Boost Amplifier\n"
				+ "Counterbalanced Compact Gyrostabilizer\n"
				+ "Covert Research Tools\n"
				+ "Crosslink Compact Ballistic Control System\n"
				+ "Cynabal Blueprint\n"
				+ "Domination EM Shield Hardener\n"
				+ "Domination Kinetic Armor Hardener\n"
				+ "Domination Tracking Enhancer\n"
				+ "Domination Warp Scrambler\n"
				+ "Dread Guristas Warp Scrambler\n"
				+ "Drone Capillary Fluid\n" + "Drone Synaptic Relay Wiring\n"
				+ "Dual 150mm Carbide Railgun I\n"
				+ "Dual 150mm Compressed Coil Gun I\n"
				+ "Dual 150mm Prototype Gauss Gun\n"
				+ "Dual 180mm Carbine Repeating Cannon I\n"
				+ "Dual 250mm Carbide Railgun I\n" + "Dual 250mm Prototype Gauss Gun\n"
				+ "Dual 425mm Carbine Repeating Cannon I\n" + "Dual Afocal Light Maser I\n"
				+ "Dual Anode Pulse Particle Stream I\n" + "Dual Heavy Anode Pulse Particle Stream I\n"
				+ "Dual Heavy Modal Pulse Laser I\n"
				+ "Electronic Engineering\n"
				+ "Elemental Crux\n"
				+ "Enduring Explosive Shield Hardener\n"
				+ "Enduring Kinetic Shield Hardener\n"
				+ "Enduring Thermal Shield Hardener\n"
				+ "Energy Cells\n" + "Extruded Compact Heat Sink\n"
				+ "Faint Epsilon Scoped Warp Scrambler\n"
				+ "Faint Scoped Warp Disruptor\n"
				+ "Firewall' Signal Amplifier Blueprint\n"
				+ "Fleeting Compact Stasis Webifier\n"
				+ "Focused Modal Medium Laser I\n"
				+ "Fourier Compact Tracking Enhancer\n"
				+ "Gallente Starship Engineering\n"
				+ "Gardan's Private Key\n"
				+ "Gatling Afocal Maser I\n"
				+ "Gila Blueprint\n"
				+ "Gistii A-Type Small Shield Booster\n"
				+ "Gistum B-Type 50MN Microwarpdrive\n" + "Gistum B-Type EM Shield Amplifier\n"
				+ "Gistum B-Type Explosive Shield Amplifier\n"
				+ "Gistum B-Type Kinetic Shield Amplifier\n"
				+ "Gistum B-Type Medium Remote Shield Booster\n"
				+ "Gistum B-Type Medium Shield Booster\n"
				+ "Gistum B-Type Multispectrum Shield Hardener\n"
				+ "Gistum B-Type Thermal Shield Amplifier\n"
				+ "Gistum C-Type 10MN Afterburner\n"
				+ "Gistum C-Type 50MN Microwarpdrive\n"
				+ "Gistum C-Type EM Shield Amplifier\n"
				+ "Gistum C-Type Explosive Shield Amplifier\n"
				+ "Gistum C-Type Kinetic Shield Amplifier\n"
				+ "Gistum C-Type Medium Remote Shield Booster\n"
				+ "Gistum C-Type Medium Shield Booster\n"
				+ "Gistum C-Type Multispectrum Shield Hardener\n"
				+ "Gistum C-Type Thermal Shield Amplifier\n"
				+ "Graviton Physics\n"
				+ "Heat Depressor\n"
				+ "Hooligan' Heavy Ion Blaster I Blueprint\n"
				+ "Initiated Compact Warp Disruptor\n"
				+ "Internal Bulkhead\n" + "Isotropic Deposition Guide\n"
				+ "J5 Enduring Warp Disruptor\n"
				+ "J5b Enduring Warp Scrambler\n"
				+ "Large C5-L Compact Shield Booster\n"
				+ "Large Clarity Ward Enduring Shield Booster\n"
				+ "Large Rudimentary Concussion Bomb I\n" + "Malkuth' Heavy Missile Launcher I\n" + "Mechanic Parts\n"
				+ "Mechanical Engineering\n"
				+ "Medium 'Notos' Explosive Charge I\n"
				+ "Medium ACM Compact Armor Repairer\n"
				+ "Medium Clarity Ward Enduring Shield Booster\n"
				+ "Medium I-a Enduring Armor Repairer\n"
				+ "Medium Rudimentary Concussion Bomb I\n"
				+ "Metal Scraps\n"
				+ "Mid-grade Ascendancy Alpha Blueprint\n"
				+ "Mid-grade Ascendancy Beta Blueprint\n"
				+ "Mid-grade Ascendancy Delta Blueprint\n"
				+ "Mid-grade Ascendancy Epsilon Blueprint\n"
				+ "Modal Light Neutron Particle Accelerator I\n" + "Monopoly' Magnetic Field Stabilizer Blueprint\n"
				+ "N-JM Compact Omnidirectional Tracking Enhancer\n"
				+ "Neural Network Analyzer\n"
				+ "Nuclear Physics\n"
				+ "Optimal Range Script\n"
				+ "Peace' Large Remote Armor Repairer Blueprint\n"
				+ "Pithum B-Type Multispectrum Shield Hardener\n"
				+ "Pithum C-Type EM Shield Amplifier\n"
				+ "Pithum C-Type Explosive Shield Amplifier\n"
				+ "Pithum C-Type Kinetic Shield Amplifier\n"
				+ "Pithum C-Type Medium Remote Shield Booster\n"
				+ "Pithum C-Type Medium Shield Booster\n"
				+ "Pithum C-Type Multispectrum Shield Hardener\n"
				+ "Pithum C-Type Thermal Shield Amplifier\n"
				+ "Plasma Physics\n"
				+ "Polarized 200mm AutoCannon Blueprint\n" + "Polarized 425mm AutoCannon Blueprint\n"
				+ "Polarized 800mm Repeating Cannon Blueprint\n"
				+ "Polarized Heavy Assault Missile Launcher Blueprint\n"
				+ "Polarized Heavy Neutron Blaster Blueprint\n"
				+ "Polarized Mega Pulse Laser Blueprint\n"
				+ "Polarized Neutron Blaster Cannon Blueprint\n" + "Polarized Rocket Launcher Blueprint\n"
				+ "Polarized Small Focused Pulse Laser Blueprint\n" + "Polarized Torpedo Launcher Blueprint\n"
				+ "Pro-Nav Compact Missile Guidance Enhancer\n" + "R.A.M.- Ammunition Tech\n"
				+ "R.A.M.- Armor/Hull Tech\n"
				+ "R.A.M.- Electronics\n"
				+ "R.A.M.- Energy Tech\n"
				+ "R.A.M.- Shield Tech\n" + "R.A.M.- Starship Tech\n" + "R.A.M.- Weapon Tech\n"
				+ "R.Db - Core Complexion\n"
				+ "R.Db - Roden Shipyards\n" + "Regulated Light Ion Phase Cannon I\n" + "Rogue Drone 46-X Nexus Chip\n"
				+ "Scratched and Dented Keycard\n" + "Second-hand Parts\n"
				+ "Shattered Villard Wheel\n"
				+ "Sleeper Data Library\n"
				+ "Sleeper Drone AI Nexus\n"
				+ "Small 'Notos' Explosive Charge I\n"
				+ "Small Clarity Ward Enduring Shield Booster\n"
				+ "Stalwart Restrained Shield Boost Amplifier\n"
				+ "Takmahl Magnetic Slab\n" + "Takmahl Solid Mox\n"
				+ "Talocan Ignition Device\n"
				+ "Talocan Mechanical Gears\n"
				+ "Talocan Partition Plates\n"
				+ "Talocan Reflective Sheets\n"
				+ "TE-2100 Ample Light Missile Launcher\n"
				+ "Titanium Sabot S\n"
				+ "Type-D Restrained Inertial Stabilizers\n"
				+ "Type-D Restrained Nanofiber Structure\n"
				+ "Type-D Restrained Overdrive Injector\n"
				+ "Vortex Compact Magnetic Field Stabilizer\n"
				+ "Whiskey' Explosive Shield Amplifier Blueprint\n"
				+ "Wild' Miner I Blueprint";
		for (String s : in.split("\n")) {
			EveType t = TypeIndex.getType(s);
			if (t != null) {
				System.out.println(t.name + "\t" + t.id);
			} else {
				System.out.println(s + "\t0");
			}
		}
	}

}
