esi:
   affiliations:
      corporation:
         update:
            skip: false
   items:
      category:
         update:
            skip: false
      group:
         update:
            skip: false
      marketgroup:
         update:
            skip: false
      type:
         update:
            skip: false
   npc:
      lpcorporation:
         update:
            skip: false
   trade:
      contract:
         info:
            update:
               skip: false
         region:
            update:
               skip: false
      market:
         update:
            skip: false
   universe:
      region:
         update:
            skip: false
      solarSystem:
         update:
            skip: false

logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
               libs:
                  spring:
                     fetchers: debug
                     trade: debug
               programs:
                  spring:
                     eveproxy: trace

mer:
   update:
      skip: true

sde:
   update:
      skip: false

spring:
   cache:
      type: simple
   datasource:
      hikari: validationTimeout:300000 # 5min timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
#debug: true