
logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
               libs:
                  spring:
                     npc: trace
                     sde: debug
                     trade: debug
                     universe: debug
                     update: debug                     
               programs:
                  spring:
                     eveproxy: trace
#      org:
#         hibernate:
#            orm:
#               jdbc:
#                  bind: trace
#            SQL: debug
#            type:
#               descriptor:
#                  sql:
#                     BasicBinder: trace

mer:
   update:
      skip: true

sde:
   fetcher:
      update:
         skip: false

spring:
   cache:
      type: simple
   datasource:
      hikari: validationTimeout:300000 # 5min timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
   jpa:
      properties:
         hibernate:
            format_sql: true
#      show-sql: true
#debug: true