
logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
               libs:
                  spring:
                     items: debug
                     npc: trace
                     sde: debug
                     trade: trace
                     universe: debug
                     update:
                        dump:
#                           Env: trace # dumps the environment
#                           Manager: trace # dumps the update managers and its entity updaters.
                        manager: trace
               programs:
                  spring:
                     eveproxy: trace

mer:
   update:
      skip: true

sde:
   fetcher:
#      force: true

spring:
   cache:
      type: simple
   datasource:
      hikari:
         validationTimeout: 10000 #10s timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
   jpa:
      properties:
         hibernate:
            format_sql: true
#      show-sql: true