
logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
               libs:
                  spring:
                     items: debug
                     npc: trace
                     sde: debug
                     trade: trace
                     universe: debug
                     update:
                        dump:
#                           Env: trace # dumps the environment
#                           Manager: trace # dumps the update managers and its entity updaters.
                        manager: trace
               programs:
                  spring:
                     eveproxy: trace

#      org:
#         hibernate:
#            orm:
#               jdbc:
#                  bind: trace
#            SQL: debug
#            type:
#               descriptor:
#                  sql:
#                     BasicBinder: trace

mer:
   update:
      skip: true

spring:
   cache:
      type: simple
   datasource:
      hikari:
         validationTimeout: 300000 # 5min timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
   jpa:
      properties:
         hibernate:
            format_sql: true
#      show-sql: true