
logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
               libs:
                  spring:
                     trade: debug
                     universe: debug
                     update: debug                     
               programs:
                  spring:
                     eveproxy: trace

mer:
   update:
      skip: true

sde:
   update:
      skip: false

spring:
   cache:
      type: simple
   datasource:
      hikari: validationTimeout:300000 # 5min timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
#debug: true