version: '3.8'
services:
   database:
      container_name: noscrape-mysql-db
      image: mysql:8.0
      environment:
      - MYSQL_DATABASE=noscrape
      - MYSQL_PASSWORD=noscrape
      - MYSQL_USER=noscrape
      ports:
      - 23306:3306
      restart: unless-stopped
      shm_size: '512mb'# actually MB
   server:
      container_name: noscrape-mysql-server
      depends_on:
      - database
      image: glechat/noscrapeve:latest
      environment:
      - SPRING_DATASOURCE_PASSWORD=noscrape
      - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/noscrape?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=noscrape
#actuators
      - management_endpoint_env_show-values=ALWAYS
      - management_endpoint_configprops_keys-to-sanitize=ALWAYS
# use memory cache
      - SPRING_CACHE_TYPE=simple
# logging
      - logging_level_fr_guiguilechat_jcelechat_libs_spring_universe_solarsystem=trace
# disable fetching of moons and asteroid belts
      - esi_universe_solarsystem_asteroidbelts=false
      - esi_universe_solarsystem_planets=false
      - esi_universe_solarsystem_moons=false
      ports:
      - 28080:8080
      restart: unless-stopped
      deploy:
         resources:
            limits:
               memory: 2000M