version: '3.8'

# start a H2 DB which writes the DB in local dir

services:
   server:
      container_name: noscrape-h2-server
      deploy:
         resources:
            limits:
               memory: 2000M
      image: glechat/noscrapeve:latest
      environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:/db/export_db
# use memory cache
      - SPRING_CACHE_TYPE=simple
      ports:
      - 18080:8080
      restart: unless-stopped
      volumes:
      - ./:/db