version: '3.8'
services:
   db:
      container_name: noscrape-postgres-db
      image: postgres:16.0-alpine
      environment:
      - POSTGRES_USER=noscrape
      - POSTGRES_PASSWORD=noscrape
      ports:
      - 45432:5432
      restart: unless-stopped
      shm_size: '512mb'# actually MB
   server:
      container_name: noscrape-postgres-server
      depends_on:
      - db
      image: glechat/noscrapeve:latest
      environment:
      - SPRING_DATASOURCE_PASSWORD=noscrape
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/noscrape
      - SPRING_DATASOURCE_USERNAME=noscrape
#actuators
      - management_endpoint_env_show-values=ALWAYS
      - management_endpoint_configprops_keys-to-sanitize=ALWAYS
# use memory cache
      - SPRING_CACHE_TYPE=simple
# logging
      - logging_level_fr_guiguilechat_jcelechat_libs_spring_universe_solarsystem=trace
# disable fetching of moons and asteroid belts
      - esi_universe_solarsystem_asteroidbelts=false
      - esi_universe_solarsystem_planets=false
      - esi_universe_solarsystem_moons=false
      ports:
      - 48080:8080
      restart: unless-stopped
      deploy:
         resources:
            limits:
               memory: 2000M