version: '3.8'
services:
   postgres:
      container_name: noscrape-postgres
      image: postgres:16.0-alpine
      environment:
      - POSTGRES_USER=noscrape
      - POSTGRES_PASSWORD=noscrape
      ports:
      - 45432:5432
      restart: unless-stopped
      shm_size: '512mb'# actually MB
   tomcat:
      container_name: noscrape-tomcat
      depends_on:
      - postgres
      image: glechat/noscrapeve:latest
      environment:
      - SPRING_DATASOURCE_PASSWORD=noscrape
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/noscrape
      - SPRING_DATASOURCE_USERNAME=noscrape
# hibernate
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=100
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_FETCH_SIZE=100
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_ORDER_INSERTS=true
# use memory cache
      - SPRING_CACHE_TYPE=simple
      ports:
      - 8080:8080
      restart: unless-stopped
      deploy:
         resources:
            limits:
               memory: 2000M