services:
   database:
      container_name: noscrape-oracle-db
      image: gvenzl/oracle-free:23.4-slim-faststart
      environment:
      - APP_USER=noscrape
      - APP_USER_PASSWORD=noscrape
      - ORACLE_PASSWORD=noscrape
      ports:
      - 31521:1521
      restart: unless-stopped
      shm_size: '512mb'# actually MB
   server:
      container_name: noscrape-oracle-server
      depends_on:
      - database
      image: glechat/noscrapeve:latest
      environment:
      - SPRING_DATASOURCE_PASSWORD=noscrape
      # default is jdbc:oracle:thin:@localhost:1521/XEPDB1
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@database:1521/FREEPDB1
      - SPRING_DATASOURCE_USERNAME=noscrape
# use memory cache
      - SPRING_CACHE_TYPE=simple
# logging
      - logging_level_fr_guiguilechat_jcelechat_libs_spring_universe_solarsystem=trace
# disable fetching of moons and asteroid belts
      - esi_universe_solarsystem_asteroidbelts=false
      - esi_universe_solarsystem_planets=false
      - esi_universe_solarsystem_moons=false
      ports:
      - 38080:8080
      restart: unless-stopped
      deploy:
         resources:
            limits:
               memory: 2000M