# working dev env. Empty tomcat to host the one we create

version: '3.8'
services:
   postgres:
      container_name: eveproxy-postgres
      image: postgres:16.0-alpine
      environment:
      - POSTGRES_USER=eveproxy
      - POSTGRES_PASSWORD=eveproxy
      ports:
      - 45432:5432
      restart: unless-stopped
      shm_size: 512mb # actually MB
   redis:
      container_name: eveproxy-redis
      deploy:
         resources:
            limits:
               memory: 1000M
      image: redis
      restart: unless-stopped
   tomcat:
      container_name: eveproxy-tomcat
      depends_on:
      - postgres
      - redis
      image: tomcat:10.1.15
      environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUTT=1000
      - SPRING_DATASOURCE_PASSWORD=eveproxy
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/eveproxy
      - SPRING_DATASOURCE_USERNAME=eveproxy
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_BATCH_SIZE=100
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_FETCH_SIZE=100
      - SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_ORDER_INSERTS=true
#        - SPRING_TASK_SCHEDULING_POOL_SIZE=10 # allow 10 parrallel @scheduled execution
      - EVEPROXY_SYNC_KILLPAGESIZE=300000
# properties of the app
      - MER_UPDATER_FETCHPERIOD=60000
      - MER_UPDATER_FETCHSIZE=20
#      - SDE_UPDATER_FORCEREINSERT=true
      ports:
      - 58080:8080
      restart: unless-stopped