types:
  37248:
    canfitshipgroup01: 1657
    canfitshipgroup02: 1404
    canfitshipgroup03: 1406
    hisecmodifier: 1.0
    hp: 40.0
    id: 37248
    lowsecmodifier: 1.2000000476837158
    marketGroup: 2345
    mass: 200.0
    maxgroupfitted: 1
    name: Standup L-Set Missile Flight Processor I
    nullsecmodifier: 1.2000000476837158
    packagedVolume: 20.0
    portionSize: 1
    published: true
    radius: 100.0
    requiredskill1: 26252
    requiredskill1level: 1
    rigsize: 3
    securitymodifier: 1
    structureitemvisualflag: 1
    structurerigmissileexplovelobonus: 30
    structurerigmissilevelocitybonus: 30
    techlevel: 1
    upgradecost: 100
    volume: 20.0
  37249:
    canfitshipgroup01: 1657
    canfitshipgroup02: 1404
    canfitshipgroup03: 1406
    hisecmodifier: 1.0
    hp: 40.0
    id: 37249
    lowsecmodifier: 1.2000000476837158
    marketGroup: 2345
    mass: 200.0
    maxgroupfitted: 1
    name: Standup L-Set Missile Flight Processor II
    nullsecmodifier: 1.2000000476837158
    packagedVolume: 20.0
    portionSize: 1
    published: true
    radius: 100.0
    requiredskill1: 26252
    requiredskill1level: 1
    rigsize: 3
    securitymodifier: 1
    structureitemvisualflag: 1
    structurerigmissileexplovelobonus: 35
    structurerigmissilevelocitybonus: 35
    techlevel: 2
    upgradecost: 150
    volume: 20.0
