types:
  Instant Booster 2X:
    id: 367596
    name: Instant Booster 2X
    portionSize: 1
    published: false
  Instant Booster 3X:
    id: 367597
    name: Instant Booster 3X
    portionSize: 1
    published: false
  Instant Booster 4X:
    id: 367598
    name: Instant Booster 4X
    portionSize: 1
    published: false
  Skill Tree Reset and Refund:
    id: 367499
    name: Skill Tree Reset and Refund
    portionSize: 1
    published: false
  instant_booster4:
    id: 367845
    name: instant_booster4
    portionSize: 1
    published: false
  mission_reroll:
    id: 367843
    name: mission_reroll
    portionSize: 1
    published: false
