#!/bin/bash

CONTAINER=noscrape-postgres-server
FILE=docker/compose/noscrape-postgresql.yml

show_usage(){
	echo usage : $0 "start|stop|logs"
	exit 0;
}

if [ "$#" -eq 0 ]; then
  show_usage
fi

case "$1" in
	start)
		docker compose -f "$FILE" up -d --build --pull always --remove-orphans
	;;
	stop)
		docker compose -f "$FILE" down --remove-orphans --rmi all -v
	;;
	log)
		docker logs -f "$CONTAINER"
	;;
	*)
		show_usage
	;;
esac