esi.alliance.info.update.skip=false
esi.character.affiliation.update.skip=false
esi.character.info.update.skip=false
esi.conflicts.war.info.update.skip=true
esi.corporation.info.update.skip=false
esi.faction.info.update.skip=false
esi.industry.costindices.update.skip=false
esi.npc.lpcorporation.update.delayUpdated=3600
esi.npc.lpcorporation.update.skip=false
esi.resolve.name.update.skip=false
esi.trade.contract.info.update.skip=false
esi.trade.contract.region.update.skip=false
esi.trade.history.update.skip=false
esi.trade.market.update.skip=false
esi.trade.prices.update.skip=false
esi.universe.statsjumps.update.skip=false
esi.universe.statskills.update.skip=false
            
everef.trade.history.update.skip=false

gameclient.fetcher.update.skip=true

jcelechat.trade.history.aggreg.update.skip=false
jcesi.manager.default.skip=true
jcesi.manager.delay=0
jcesi.manager.period=2000

sde.fetcher.update.skip=false

spring.task.scheduling.pool.size=10