types:
  367499:
    id: 367499
    name: Skill Tree Reset and Refund
    portionSize: 1
    published: false
  367596:
    id: 367596
    name: Instant Booster 2X
    portionSize: 1
    published: false
  367597:
    id: 367597
    name: Instant Booster 3X
    portionSize: 1
    published: false
  367598:
    id: 367598
    name: Instant Booster 4X
    portionSize: 1
    published: false
  367843:
    id: 367843
    name: mission_reroll
    portionSize: 1
    published: false
  367845:
    id: 367845
    name: instant_booster4
    portionSize: 1
    published: false
