#!/bin/bash
# deploy to the tomcat specified in the remote fold.

source $HOME/.config/MEvEtic/remote.cfg\
&& mvn clean package\
&& scp target/MEvEtic.war $RMT_SSH:\
&& ssh $RMT_SSH mv MEvEtic.war /var/lib/tomcat10/webapps/

