#!/bin/bash
# deploy to the tomcat specified in the remote fold.

source $HOME/.config/EveProxy/remote.cfg\
&& mvn clean package\
&& scp target/EveProxy.war $RMT_SSH:\
&& ssh $RMT_SSH mv EveProxy.war /var/lib/tomcat10/webapps/

