esi:
   items:
      attribute:
         update:
            max: 800
            skip: false
      category:
         update:
            skip: false
      effect:
         update:
            skip: false
      group:
         update:
            skip: false
      type:
         update:
            max: 1000
            delay: 0
            skip: false
   universe:
      moon:
         update:
            max: 1200
      planet:
         update:
            skip: false
      region:
         update:
            skip: false
      solarSystem:
         planets: true
         moons: true
      star:
         update:
            skip: false
      stargate:
         update:
            skip: false
      station:
         update:
            skip: false
   updater:
      default:
         skip: false
      delay: 0
      period: 2000
      skip: false

jcelechat:
   noscrape:
      oncomplete:
         stop: false

logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
spring:
   cache:
      type: simple
   datasource:
      hikari: validationTimeout:300000 # 5min timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
   jpa:
      generate-ddl: true
      hibernate:
         ddl-auto: update
      open-in-view: false
      properties:
         hibernate:
            jdbc:
               batch_size: 50
               fetch_size: 50
            order_insert: true