esi:
   items:
      category:
         update:
            skip: false
      attribute:
         update:
            max: 1000
      type:
         update:
            max: 1000
   universe:
      region:
         update:
            skip: false
   updater:
      default:
         skip: true
      delay: 0
      period: 5000
      skip: false

jcelechat:
   noscrape:
      oncomplete:
         stop: true

logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: INFO
spring:
   cache:
      type: simple
   datasource:
      hikari: validationTimeout:300000 # 5min timeout for access local h2 DB
      password: admin
      url: jdbc:h2:./db/export
      username: admin
   jpa:
      generate-ddl: true
      hibernate:
         ddl-auto: update
      open-in-view: false
      properties:
         hibernate:
            jdbc:
               batch_size: 50
               fetch_size: 50
            order_insert: true