
jcelechat:
   noscrape:
      oncomplete:
         stop: false

jcesi:
   updater:
#      default:
#         skip: true # default is true
      delay: 0
      period: 2000
#      skip: false #default is false

logging:
   level:
      fr:
         guiguilechat:
            jcelechat:
               jcesi: infos
               libs:
                  spring:
                     update: debug

sde:
   fetcher:
      force: true
      update:
         skip: false
   space:
      moon.skip: true

spring:
   cache:
      type: simple
   datasource:
      password: admin
      url: jdbc:h2:./db/export
      username: admin
