version: '3.8'

# start a H2 DB which writes the DB in local dir

services:
   server:
      container_name: eveproxy-h2-server
      deploy:
         resources:
            limits:
               memory: 16G
      image: glechat/eveproxy:latest
      environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:/db/eveproxy_h2_db
# use memory cache
      - SPRING_CACHE_TYPE=simple
# logging
      - logging.level.fr.guiguilechat.jcelechat.libs.spring.trade=debug
      ports:
      - 18080:8080
      restart: unless-stopped
      volumes:
      - ./:/db