# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
   push:
      tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
   build:

      runs-on: ubuntu-latest
      permissions:
         contents: read
         packages: write

      steps:
#checkout the git commit
      -  uses: actions/checkout@v4

# set maven information to export (create a settings.xml with server access using variables)
      -  name: Set up JDK
         uses: actions/setup-java@v4
         with:
            java-version: '24'
            distribution: temurin
            server-id: github-guiguilechat-jcelechat # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file

# run the maven push
# profile skipDeployPom skips the deploy phase in pom modules
# -ntp to avoid flooding with transfert rates
# use the afformentioned settings.xml to connect
# ignore certificate issues for repositories that are https
      -  name: Publish to GitHub Packages Apache Maven
#         run: cat $GITHUB_WORKSPACE/settings.xml
         run: >
            mvn -PskipDeployPom deploy -ntp -s $GITHUB_WORKSPACE/settings.xml
            -Dmaven.resolver.transport=wagon -Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true
         env:
            GH_JCELECHAT: ${{ vars.GH_REPO }}
            GITHUB_TOKEN: ${{ github.token }}
            EVEPROXY_DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
            EVEPROXY_DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
            MEVETIC_DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
            MEVETIC_DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}
            NOSCRAPEVE_DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
            NOSCRAPEVE_DOCKER_HUB_USER: ${{ vars.DOCKER_HUB_USER }}